baseurl = "/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "Home"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[menu]

[[menu.main]]
    name = "Home | Inicio"
    url = "/"
    weight = 6

  [[menu.main]]
    name = "Photos | Fotos"
    url = "/photos/"
    weight = 5

  [[menu.main]]
    name = "Newsletters | Boletín"
    url = "/newsletters/"
    weight = 4
  
  [[menu.main]]
    name = "Events | Eventos"
    url = "/events/"
    weight = 3

  [[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 2

  [[menu.main]]
    name = "Join Us | Únete"
    url = "/join/"
    weight = 1

[params]
custom_css = ["css/theme-override.css"]
description = "A simple, minimal blog for those who love text."
footer = "Carter-Riverside Neighborhood Association, site run by member Erick C. Jones Jr."
